apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asr
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
      - name: asr
        image: mailong25/asr-server:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            nvidia.com/gpu: 1  # Request one GPU
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3