apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: overprovisioner
value: 500000
globalDefault: false
description: "Priority for overprovisioner pods"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: asr-app
value: 1000000
globalDefault: false
description: "Priority for critical app pods"
